#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

cargo generate-lockfile

git init

mkdir .git/info
echo "/tmp.rs" > .git/info/exclude

./setup-dev-environment

git add .
git commit -m "🎉 initial commit"

mkdir assets
