default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    exclude: 'ts//{{cookiecutter.project_name}}///.yarn/.*'
  - id: check-case-conflict
  - id: check-symlinks
