#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

{% if cookiecutter.with_main %}
echo "fn main() {}" > src/main.rs
echo "# Run the project using cargo\n[no-exit-message]\nrun:\n  cargo run" >> justfile
{% endif %}

cargo generate-lockfile

git init

mkdir .git/info
echo "/tmp.rs" > .git/info/exclude

./setup-dev-environment

git add .
git commit -m "chore: initial commit"

touch local.justfile
