#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

{% if cookiecutter.with_main %}
echo "fn main() {}" > src/main.rs
{% endif %}

cargo generate-lockfile

git init

mkdir .git/info
echo "/tmp.rs" > .git/info/exclude

./setup-dev-environment

git add .
git commit -m "chore: initial commit"
