#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

echo "exclude: '^(.yarn/|.pnp.cjs)'" \
    | cat - .pre-commit-config.yaml \
    > .pre-commit-config.yaml.tmp

mv .pre-commit-config.yaml.tmp .pre-commit-config.yaml

yarn

git init
./setup-dev-environment
git add .
git commit -m "chore: initial commit"
