[package]
name = "{{ cookiecutter.project_name }}"
authors = ["{{ cookiecutter.author }} <{{ cookiecutter.email }}>"]
version = "0.1.0-dev"
edition = "2021"
description = "{{ cookiecutter.description }}"
license = "MIT OR APACHE"

[dependencies]
