[package]
name = "{{ cookiecutter.project_name }}"
authors = ["{{ cookiecutter.author }} <{{ cookiecutter.email }}>"]
version = "0.0.0"
edition = "2021"
description = "{{ cookiecutter.description }}"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
