flags := "--features=dev"
alias lint := clippy

[private]
@default:
  just --list --justfile {{justfile()}}

# Build the project using cargo
[no-exit-message]
build:
  cargo build

# Run the project using cargo
[no-exit-message]
run:
  cargo run

# Test the project using cargo
[no-exit-message]
test:
  cargo nextest run {{flags}}

# Run clippy on the project
[no-exit-message]
clippy:
  cargo clippy {{flags}}

# Build documentation using rustdoc
[no-exit-message]
doc:
  cargo rustdoc {{flags}}
