#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

# add properties to package.json
jq -s '.[0] * .[1]' package.json package.merge.json > tmp.json
rm package.merge.json
mv tmp.json package.json

# add properties to nx.json
jq -s '.[0] * .[1]' nx.json nx.merge.json > tmp.json
rm nx.merge.json
mv tmp.json nx.json


echo "exclude: '^(\.yarn/|\.pnp\..*)'" \
    | cat - .pre-commit-config.yaml \
    > .pre-commit-config.yaml.tmp
mv .pre-commit-config.yaml.tmp .pre-commit-config.yaml


yarn
yarn nx format

./setup-dev-environment

git add .
pre-commit run trailing-whitespace || true
git add .
git commit -m "chore: initial commit"
