#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

readonly project_name='{{ cookiecutter.project_name }}'
readonly scope='{{ cookiecutter.npm_scope }}'

cd ..

yarn create nx-workspace "${project_name}" \
    --style="scss" --preset=apps --npmScope="${scope}" \
    --defaultBase=master --skipInstall --commit=false \
    --packageManager=yarn --nxCloud=false

cd "${project_name}"

rm .prettierrc .prettierignore
ln -s .eslintignore .prettierignore
